// skill verb — distribute the embedded agent skill. Three subcommands:
//
//	skill install [--target <dir>] — copy the skill into an agent skill
//	  directory (default ~/.agents/skills/scipq, the AgentSkills location
//	  scanned by OpenClaw, Copilot user scope, and Claude-compatible
//	  loaders). Idempotent: re-running refreshes the copy in place.
//	  Writes only skill directories it owns the naming for — never edits
//	  user files (instructions files get the snippet block via an
//	  explicit, reviewable copy of `skill snippet` output).
//	skill print [page] [--list] — emit embedded skill content to stdout.
//	  The zero-install read path for any agent with shell access.
//	skill snippet [--json] — emit a ready-to-paste markdown block for
//	  repo instructions files (Copilot-style consumers).
//
// All paths are projections of the embedded copy; nothing is fetched.
// No index is loaded — skill operates before/outside the index contract.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	scipq "github.com/elodhorvath/scipq"

	"github.com/urfave/cli/v3"
)

// skillVersion is the embedded skill's version: the binary's version,
// injected at release build time by goreleaser via
// -ldflags "-X main.skillVersion={{ .Tag }}" (.goreleaser.yaml) — the full
// tag (e.g. "v0.4.0"), matching the install command's form; dev builds
// report "dev". The installed copy carries a
// .scipq-version marker with this value — filesystem-side skew
// detection, since agents won't run `scipq skill` to check.
var skillVersion = "dev"

// skillMarkerFile is written into the installed skill directory holding
// skillVersion (plain string). It lets any consumer detect skew between
// the installed copy and the binary that installed it.
const skillMarkerFile = ".scipq-version"

// embedPath joins skill-root-relative elements into an embedded-FS path.
// embed.FS implements io/fs, whose paths are slash-separated by
// definition — a backslash is an ordinary filename character, not a
// separator — so embedded addressing uses the path package exclusively.
// filepath (host separators) is reserved for install-target filesystem
// paths; mixing them breaks every lookup on Windows, where filepath
// always emits backslashes (pre-commit review blocker 1).
func embedPath(rel ...string) string {
	return path.Join(append([]string{scipq.SkillRoot}, rel...)...)
}

// skillSnippet is the instructions-file block emitted by `skill snippet`:
// the decision table, the agent-UX contract summary, the indexing rule,
// and the pointer to `scipq skill print` for the full text. It is a
// projection of the skill's content, kept in lockstep by the same-PR
// rule; the full skill remains the contract.
const skillSnippet = `<!-- scipq skill snippet (generated by scipq skill snippet; refresh with the same command) -->
## scipq — code-graph queries over a SCIP index

` + "`scipq`" + ` answers structural code questions (who uses X, what breaks if I
change X, what is dead) from a SCIP index (` + "`index.scip`" + `) instead of
reading source files. Reach for it **before** opening source files whenever
the question is structural (who/where/how-many), not textual.

| Question | Verb |
|---|---|
| Who uses / references / calls X? Who implements this interface? | ` + "`callers`" + ` |
| What is this repo/package? Where are the hubs and hotspots? | ` + "`map`" + ` |
| What breaks if I change X? (given a diff) | ` + "`blast`" + ` |
| What's this file's API surface? | ` + "`skeleton`" + ` |
| What's defined but never referenced? | ` + "`dead`" + ` |

Agent-UX contract (pinned): ` + "`--json`" + ` is the machine mode (stdout is data
only); exit codes 0 success / 1 usage error / 2 missing index; ` + "`--index`" + ` and
` + "`--json`" + ` are persistent root flags; every failure prints a ` + "`scipq:`" + `
-prefixed stderr diagnostic. Out-of-root documents are filtered at load.

Indexing rule: scipq consumes indexes, it does not build them. If no
` + "`index.scip`" + ` exists and one cannot be built, say so and ask — never
silently fall back to grep and present textual matches as graph answers.
Rebuild the index after branch switches and before ` + "`blast`" + ` on a fresh
diff session; stale-index sign: symbols visible in source missing from
query results.

Full skill text (decision policy, per-verb reference, indexing playbook):
run ` + "`scipq skill print`" + ` (main file), ` + "`scipq skill print --list`" + `
(page inventory), or ` + "`scipq skill print <page>`" + ` (e.g.
` + "`scipq skill print callers`" + `). Install into an agent skills directory
with ` + "`scipq skill install`" + `.
`

// skillCommand builds the `skill` command group. It never loads an
// index: distribution is independent of any SCIP file.
func skillCommand() *cli.Command {
	return &cli.Command{
		Name:  "skill",
		Usage: "install, print, or snippet the embedded agent skill",
		Commands: []*cli.Command{
			skillInstallCommand(),
			skillPrintCommand(),
			skillSnippetCommand(),
		},
		// Bare `scipq skill` prints the embedded version and subcommand
		// usage (issue #54 pin 3: minimal surface).
		Action: func(_ context.Context, cmd *cli.Command) error {
			if args := cmd.Args(); args.Len() > 0 {
				fmt.Fprintf(stderr, "scipq: unknown skill subcommand %q\n", args.First())
				skillUsage(stderr)
				return &exitError{code: exitUsage}
			}
			skillUsage(stdout)
			return nil
		},
		OnUsageError: usageError,
	}
}

// skillUsage writes the skill group's usage line: embedded version,
// subcommands, and the default install target.
func skillUsage(w io.Writer) {
	fmt.Fprintf(w, "scipq skill — embedded agent skill, version %s\n", skillVersion)
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "usage: scipq skill <subcommand> [args]")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "subcommands: install, print, snippet")
	fmt.Fprintf(w, "install default target: %s\n", defaultSkillTarget())
	fmt.Fprintln(w, "run 'scipq skill <subcommand> -h' for subcommand help")
}

// defaultSkillTarget derives the default install root from $HOME —
// never a hardcoded absolute path (portability criterion). The trailing
// /scipq names the directory scipq owns the naming for.
func defaultSkillTarget() string {
	home, err := os.UserHomeDir()
	if err != nil {
		// No resolvable home: there is no default target. install
		// requires --target in that environment; the error surfaces
		// there, not here (bare `skill` must still print usage).
		return "none (--target required; home directory not resolvable)"
	}
	return filepath.Join(home, ".agents", "skills", "scipq")
}

// skillInstallCommand implements `scipq skill install [--target <dir>]`.
func skillInstallCommand() *cli.Command {
	return &cli.Command{
		Name:  "install",
		Usage: "copy the embedded skill into an agent skills directory",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "target",
				Usage: "destination skill directory (default ~/.agents/skills/scipq)",
			},
		},
		OnUsageError: usageError,
		Action: func(_ context.Context, cmd *cli.Command) error {
			if args := cmd.Args(); args.Len() > 0 {
				fmt.Fprintf(stderr, "scipq: skill install takes no positional arguments (got %q)\n", cmd.Args().Slice())
				return &exitError{code: exitUsage}
			}
			w := newWriter(cmd.Bool("json"))
			target := cmd.String("target")
			if target == "" {
				home, err := os.UserHomeDir()
				if err != nil {
					fmt.Fprintf(w.err, "scipq: resolve home directory: %v (pass --target <dir>)\n", err)
					return &exitError{code: exitUsage}
				}
				target = filepath.Join(home, ".agents", "skills", "scipq")
			}
			files, err := installSkill(target)
			if err != nil {
				fmt.Fprintf(w.err, "scipq: %v\n", err)
				return &exitError{code: exitUsage}
			}
			if cmd.Bool("json") {
				res := skillInstallResult{
					Target:  target,
					Version: skillVersion,
					Files:   files,
				}
				enc := json.NewEncoder(w.out)
				enc.SetIndent("", "  ")
				if err := enc.Encode(res); err != nil {
					fmt.Fprintf(w.err, "scipq: encode json: %v\n", err)
					return &exitError{code: exitUsage}
				}
				return nil
			}
			fmt.Fprintf(w.out, "installed scipq skill (%s) → %s (%d files)\n", skillVersion, target, len(files))
			return nil
		},
	}
}

// skillInstallResult is the --json shape of `skill install`.
type skillInstallResult struct {
	Target  string   `json:"target"`
	Version string   `json:"version"`
	Files   []string `json:"files"`
}

// installSkill copies the embedded skill tree into target (created if
// missing), unconditionally overwriting — idempotent refresh after a
// binary upgrade, no --force gate (the skill is small, version-matched,
// and re-installable). A .scipq-version marker (plain version string) is
// written for filesystem-side skew detection. Returns the installed
// file paths (target-relative, sorted, marker included). Directories
// 0755, files 0644.
func installSkill(target string) ([]string, error) {
	// Create the target root up front: the copy loop only MkdirAlls
	// subdirectories, and a fresh target must exist before the first
	// file write.
	if err := os.MkdirAll(target, 0o755); err != nil {
		return nil, fmt.Errorf("create %s: %w", target, err)
	}
	entries, err := fs.ReadDir(scipq.SkillFS, scipq.SkillRoot)
	if err != nil {
		return nil, fmt.Errorf("read embedded skill: %w", err)
	}
	var installed []string
	// Walk the embedded tree deterministically: ReadDir sorts by name,
	// and recursion preserves per-directory order. rel starts empty —
	// the skill root maps onto target itself.
	for _, e := range entries {
		files, err := copyEmbeddedDir(scipq.SkillRoot, e, target, "")
		if err != nil {
			return nil, err
		}
		installed = append(installed, files...)
	}
	if err := os.WriteFile(filepath.Join(target, skillMarkerFile), []byte(skillVersion+"\n"), 0o644); err != nil {
		return nil, fmt.Errorf("write version marker: %w", err)
	}
	installed = append(installed, skillMarkerFile)
	sort.Strings(installed)
	return installed, nil
}

// copyEmbeddedDir recursively copies one embedded directory entry into
// the corresponding path under destRoot, creating directories 0755 and
// files 0644. rel is the slash-separated, skill-root-relative embedded
// path being written (also used as the target-relative install path —
// the installed layout mirrors the embedded layout, and slash paths are
// valid relative paths on every supported host). Returns the
// target-relative file paths written (sorted by walk order).
func copyEmbeddedDir(root string, e fs.DirEntry, destRoot, rel string) ([]string, error) {
	relPath := path.Join(rel, e.Name())
	if e.IsDir() {
		dir := filepath.Join(destRoot, filepath.FromSlash(relPath))
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, fmt.Errorf("create %s: %w", relPath, err)
		}
		entries, err := fs.ReadDir(scipq.SkillFS, embedPath(relPath))
		if err != nil {
			return nil, fmt.Errorf("read embedded %s: %w", relPath, err)
		}
		var installed []string
		for _, child := range entries {
			files, err := copyEmbeddedDir(root, child, destRoot, relPath)
			if err != nil {
				return nil, err
			}
			installed = append(installed, files...)
		}
		return installed, nil
	}
	src, err := scipq.SkillFS.ReadFile(embedPath(relPath))
	if err != nil {
		return nil, fmt.Errorf("read embedded %s: %w", relPath, err)
	}
	dst := filepath.Join(destRoot, filepath.FromSlash(relPath))
	if err := os.WriteFile(dst, src, 0o644); err != nil {
		return nil, fmt.Errorf("write %s: %w", relPath, err)
	}
	return []string{relPath}, nil
}

// skillPrintCommand implements `scipq skill print [page] [--list]`.
func skillPrintCommand() *cli.Command {
	return &cli.Command{
		Name:      "print",
		Usage:     "print embedded skill content to stdout (bare or SKILL.md: main file; verb name: its reference page; path: exact embedded path)",
		UsageText: "scipq skill print [page] [--list]",
		Flags: []cli.Flag{
			&cli.BoolFlag{
				Name:  "list",
				Usage: "print the embedded page inventory (skill-root-relative paths, sorted) instead of page content",
			},
		},
		OnUsageError: usageError,
		Action: func(_ context.Context, cmd *cli.Command) error {
			args := cmd.Args()
			if args.Len() > 1 {
				fmt.Fprintf(stderr, "scipq: skill print takes at most one page argument (got %q)\n", args.Slice())
				return &exitError{code: exitUsage}
			}
			w := newWriter(cmd.Bool("json"))
			if cmd.Bool("list") {
				if args.Len() > 0 {
					fmt.Fprintf(w.err, "scipq: --list takes no page argument\n")
					return &exitError{code: exitUsage}
				}
				pages, err := listSkillPages()
				if err != nil {
					fmt.Fprintf(w.err, "scipq: %v\n", err)
					return &exitError{code: exitUsage}
				}
				for _, p := range pages {
					fmt.Fprintln(w.out, p)
				}
				return nil
			}
			page := ""
			if args.Len() == 1 {
				page = args.First()
			}
			content, err := resolveSkillPage(page)
			if err != nil {
				fmt.Fprintf(w.err, "scipq: %v\n", err)
				return &exitError{code: exitUsage}
			}
			// Raw bytes of the embedded file: no frontmatter stripping,
			// no re-wrapping — the file is the contract.
			if _, err := w.out.Write(content); err != nil {
				fmt.Fprintf(w.err, "scipq: write page: %v\n", err)
				return &exitError{code: exitUsage}
			}
			return nil
		},
	}
}

// listSkillPages returns the embedded skill's page inventory:
// skill-root-relative slash paths, sorted. The fixture asserts this
// against the actual embedded FS (issue #54: assert real content, not
// existence). The embedded FS is compile-time constant, so a walk
// error is an invariant violation — but the error is returned, not
// panicked, so the verb can fail with its normal diagnostic contract
// (nonzero exits are never silent, never crash).
func listSkillPages() ([]string, error) {
	var pages []string
	err := fs.WalkDir(scipq.SkillFS, scipq.SkillRoot, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		// WalkDir yields paths under the walk root; strip the skill-root
		// prefix (slash-based — io/fs paths are slash-separated).
		rel := strings.TrimPrefix(p, scipq.SkillRoot+"/")
		pages = append(pages, rel)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk embedded skill: %w", err)
	}
	sort.Strings(pages)
	return pages, nil
}

// resolveSkillPage resolves a `skill print` page argument to the
// embedded file's bytes, per the issue #54 resolution contract (first
// match wins, no globbing):
//
//  1. Empty or "SKILL.md" → the main skill file.
//  2. Anything with a slash → exact embedded path, relative to the
//     skill root (e.g. reference/verbs/map.md, reference/indexing.md).
//  3. Short name → reference/verbs/<name>.md, then reference/<name>.md,
//     then <name>.md at the skill root.
//
// `..` components and absolute paths are rejected before resolution —
// the embedded FS is the only namespace. No match exits with an error
// listing the available pages (sorted); never a closest-match guess.
func resolveSkillPage(page string) ([]byte, error) {
	if page == "" || page == "SKILL.md" {
		return scipq.SkillFS.ReadFile(embedPath("SKILL.md"))
	}
	// Reject traversal and absolute forms before any resolution: the
	// embedded FS is the only namespace (same predicate class as the
	// out-of-root document filter — there it protects index truth, here
	// the embedded boundary). The cleaned path is slash-normalized, so
	// the traversal prefix check is separator-independent.
	if filepath.IsAbs(page) || strings.HasPrefix(page, "~") {
		return nil, fmt.Errorf("invalid page %q: absolute paths are not resolvable inside the embedded skill (use a skill-root-relative path, e.g. reference/verbs/map.md)", page)
	}
	clean := path.Clean(filepath.ToSlash(page))
	if clean == ".." || strings.HasPrefix(clean, "../") {
		return nil, fmt.Errorf("invalid page %q: path traversal outside the embedded skill", page)
	}
	if strings.Contains(clean, "/") {
		// Exact embedded path.
		b, err := scipq.SkillFS.ReadFile(embedPath(clean))
		if err != nil {
			return nil, noSkillPageErr(page)
		}
		return b, nil
	}
	// Short name against fixed precedence.
	for _, cand := range []string{
		path.Join("reference", "verbs", clean+".md"),
		path.Join("reference", clean+".md"),
		clean + ".md",
	} {
		if b, err := scipq.SkillFS.ReadFile(embedPath(cand)); err == nil {
			return b, nil
		}
	}
	return nil, noSkillPageErr(page)
}

// noSkillPageErr builds the no-match diagnostic: the page argument plus
// the sorted available-page inventory. Used for both short-name and
// exact-path misses — the resolution pin requires the inventory on
// every no-match, not just the short-name fallback.
func noSkillPageErr(page string) error {
	pages, err := listSkillPages()
	if err != nil {
		return err
	}
	return fmt.Errorf("no skill page %q — available pages:\n  %s", page, strings.Join(pages, "\n  "))
}

// skillSnippetCommand implements `scipq skill snippet [--json]`.
func skillSnippetCommand() *cli.Command {
	return &cli.Command{
		Name:         "snippet",
		Usage:        "emit a ready-to-paste markdown block for repo instructions files (e.g. .github/copilot-instructions.md)",
		OnUsageError: usageError,
		Action: func(_ context.Context, cmd *cli.Command) error {
			if args := cmd.Args(); args.Len() > 0 {
				fmt.Fprintf(stderr, "scipq: skill snippet takes no positional arguments (got %q)\n", cmd.Args().Slice())
				return &exitError{code: exitUsage}
			}
			w := newWriter(cmd.Bool("json"))
			if cmd.Bool("json") {
				enc := json.NewEncoder(w.out)
				enc.SetIndent("", "  ")
				if err := enc.Encode(skillSnippetResult{Snippet: skillSnippet}); err != nil {
					fmt.Fprintf(w.err, "scipq: encode json: %v\n", err)
					return &exitError{code: exitUsage}
				}
				return nil
			}
			if _, err := io.WriteString(w.out, skillSnippet); err != nil {
				fmt.Fprintf(w.err, "scipq: write snippet: %v\n", err)
				return &exitError{code: exitUsage}
			}
			return nil
		},
	}
}

// skillSnippetResult is the --json shape of `skill snippet`.
type skillSnippetResult struct {
	Snippet string `json:"snippet"`
}
